#!/usr/bin/env bash
# Vérifie si un argument (adresse IP) a été passé au script
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"  # Affiche la manière d'utiliser le script si aucun argument n'est fourni
    exit 1  # Quitte le script avec un code d'erreur
fi

# Envoie 5 paquets ping à l'adresse IP fournie
ping -c 5 "$1"  # "$1" correspond au premier argument passé au script (adresse IP)
