#!/usr/bin/env bash
# Afficher toutes les adresses IPv4 actives de la machine
# ifconfig = affiche la configuration des interfaces réseau
# awk '/inet / {print $2}' = cherche les lignes contenant "inet " et affiche le 2ème champ (l'IP)
# Plus simple et efficace que grep + awk
ifconfig | awk '/inet / {print $2}'
